apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblogic-extranet-dev-pvc
  namespace: weblogic-extranet-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeName: ""
